name: cadvisor

services:
    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor
        restart: unless-stopped
        privileged: true
        environment:
            TZ: "${TZ:-Europe/Warsaw}"
        # ports:
        #     - ${CADVISOR_BIND_IP:-127.0.0.1}:${CADVISOR_PORT:-8080}:8080
        hostname: cadvisor
        networks:
            shared-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        devices:
            - /dev/kmsg
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        tty: true

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true
