name: node-exporter

services:
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter
        restart: unless-stopped
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/rootfs"
            - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
        environment:
            TZ: "${TZ:-Europe/Warsaw}"
        # ports:
        #     - ${NODE_EXPORTER_PORT:-9100}:9100
        hostname: node-exporter
        networks:
            shared-network-internal:
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        tty: true

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_INTERNAL_NAME:-shared-network-internal}
        external: true
