services:
    affine:
        container_name: affine
        image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
        restart: unless-stopped
        depends_on:
            affine_migration:
                condition: service_completed_successfully
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            REDIS_SERVER_HOST: "${REDIS_SERVER_HOST:-valkey}"
            REDIS_SERVER_PASSWORD: "${REDIS_SERVER_PASSWORD:-zaq1@WSX}"
            DATABASE_URL: "${DATABASE_URL:-postgresql://affine:affine@postgres:5432/affine}"
            AFFINE_INDEXER_ENABLED: "${AFFINE_INDEXER_ENABLED:-true}"
            AFFINE_SERVER_HTTPS: "${AFFINE_SERVER_HTTPS:-true}"
            AFFINE_SERVER_HOST: "${AFFINE_SERVER_HOST:-affine.localhost}"
        # ports:
        #     - ${AFFINE_PORT:-3010}:3010
        hostname: "${DOMAIN:-affine.localhost}"
        networks:
            main:
        volumes:
            - affine-storage:/root/.affine/storage
            - affine-conf:/root/.affine/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.affine.loadbalancer.server.port=3010"
            - "traefik.http.routers.affine.rule=Host(`${DOMAIN:-affine.localhost}`)"
            - "traefik.http.routers.affine.entrypoints=http"
            - "traefik.http.routers.affine.tls=false"
            - "traefik.http.routers.affine.service=affine"
            - "traefik.http.routers.affine-secure.rule=Host(`${DOMAIN:-affine.localhost}`)"
            - "traefik.http.routers.affine-secure.entrypoints=https"
            - "traefik.http.routers.affine-secure.tls=true"
            - "traefik.http.routers.affine-secure.service=affine"

    affine_migration:
        container_name: affine_migration
        image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
        command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            REDIS_SERVER_HOST: "${REDIS_SERVER_HOST:-valkey}"
            REDIS_SERVER_PASSWORD: "${REDIS_SERVER_PASSWORD:-zaq1@WSX}"
            DATABASE_URL: "${DATABASE_URL:-postgresql://affine:affine@postgres:5432/affine}"
            AFFINE_INDEXER_ENABLED: "${AFFINE_INDEXER_ENABLED:-true}"
            AFFINE_SERVER_HTTPS: "${AFFINE_SERVER_HTTPS:-true}"
            AFFINE_SERVER_HOST: "${AFFINE_SERVER_HOST:-affine.localhost}"
        networks:
            main:
        volumes:
            - affine-storage:/root/.affine/storage
            - affine-conf:/root/.affine/config

networks:
    main:
        external: true

volumes:
    affine-storage:
        name: affine-storage
    affine-conf:
        name: affine-conf
