name: adminer

services:
    php:
        container_name: adminer-php
        build:
            context: .
            dockerfile: ./Dockerfile
            target: app
            network: host
            args:
                TZ: ${TZ:-Europe/Warsaw}
                USER: ${APP_USER:-app}
                GROUP: ${APP_GROUP:-app}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: unless-stopped
        environment:
            HOME: /home/${APP_USER:-app}
            PHP_IDE_CONFIG: "serverName=adminer.localhost"
        tty: true
        networks:
            shared-network:
        volumes:
            - caddy-data:/data
            - caddy-config:/config
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html
            - ./configs/php.ini:/usr/local/etc/php/php.ini
            - ./configs/Caddyfile:/etc/frankenphp/Caddyfile
        labels:
            traefik.enable: true
            traefik.http.services.adminer.loadbalancer.server.port: 80
            traefik.http.services.adminer-secure.loadbalancer.server.port: 443
            traefik.http.routers.adminer.rule: Host(`${DOMAIN:-adminer.localhost}`)
            traefik.http.routers.adminer.entrypoints: http
            traefik.http.routers.adminer.tls: false
            traefik.http.routers.adminer.service: adminer
            traefik.http.routers.adminer-secure.rule: Host(`${DOMAIN:-adminer.localhost}`)
            traefik.http.routers.adminer-secure.entrypoints: https
            traefik.http.routers.adminer-secure.tls: true
            traefik.http.routers.adminer-secure.service: adminer-secure

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-data:
        name: adminer-caddy-data
    caddy-config:
        name: adminer-caddy-config
