services:
    adminer:
        container_name: adminer
        image: adminer
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            ADMINER_PLUGINS: "${ADMINER_PLUGINS:-dump-alter dump-bz2 dump-date dump-json dump-xml dump-zip edit-foreign edit-textarea enum-option foreign-system frames json-column slugify sql-log tables-filter}"
        # ports:
        #     - ${ADMINER_PORT:-8080}:8080
        hostname: "${DOMAIN:-adminer.localhost}"
        networks:
            main:
        labels:
            traefik.enable: "true"
            traefik.http.services.adminer.loadbalancer.server.port: "8080"
            traefik.http.routers.adminer.rule: "Host(`${DOMAIN:-adminer.localhost}`)"
            traefik.http.routers.adminer.entrypoints: "http"
            traefik.http.routers.adminer.tls: "false"
            traefik.http.routers.adminer.service: "adminer"
            traefik.http.routers.adminer-secure.rule: "Host(`${DOMAIN:-adminer.localhost}`)"
            traefik.http.routers.adminer-secure.entrypoints: "https"
            traefik.http.routers.adminer-secure.tls: "true"
            traefik.http.routers.adminer-secure.service: "adminer"

networks:
    main:
        external: true
