tls:
    options:
        default:
            sniStrict: false
    certificates:
        - certFile: "/etc/certs/local-cert.pem"
          keyFile: "/etc/certs/local-key.pem"
          stores:
              - default
    stores:
        default:
            defaultCertificate:
                certFile: "/etc/certs/local-cert.pem"
                keyFile: "/etc/certs/local-key.pem"
