global:
    sendAnonymousUsage: false

api:
    dashboard: true
    insecure: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        exposedByDefault: false

    file:
        filename: /etc/traefik/dynamic.yaml
        watch: true

log:
    level: DEBUG
    format: common

entryPoints:
    traefik:
        address: ":8999"
    http:
        address: ":80"
        # http:
        #     redirections:
        #         entryPoint:
        #             to: https
        #             scheme: https
    https:
        address: ":443"
    port5173:
        address: ":5173"
