name: redis8

services:
    redis8:
        container_name: redis8
        image: redis:8-trixie
        restart: unless-stopped
        command: redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD:-secret}"
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TZ:-Europe/Warsaw}"
        # ports:
        #     - ${REDIS_BIND_IP:-127.0.0.1}:${REDIS_PORT:-6308}:6379
        networks:
            shared-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - redis8-data:/data
        tty: true

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    redis8-data:
        name: redis8-data
