name: base-alpine

services:
    base-alpine:
        container_name: base-alpine
        build:
            context: .
            dockerfile: ./Dockerfile
            target: prod
            args:
                TZ: ${TZ:-Europe/Warsaw}
                USER: ${APP_USER:-app}
                GROUP: ${APP_GROUP:-app}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: no
        # user: "${UID:-1000}:${GID:-1000}"
        tty: true
        networks:
            shared-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
