services:
    devbox:
        container_name: devbox
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        user: "${UID:-1000}:${GID:-1000}"
        tty: true
        networks:
            shared-network-internal:
        volumes:
            - shared-home:/home/${APP_USER:-app}

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_INTERNAL_NAME:-shared-network-internal}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
