name: valkey7

services:
    valkey7:
        container_name: valkey7
        image: valkey/valkey:7-trixie
        restart: unless-stopped
        command: valkey-server --save 60 1 --loglevel warning --requirepass "${VALKEY_PASSWORD:-secret}"
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TZ:-Europe/Warsaw}"
        # ports:
        #     - ${VALKEY_BIND_IP:-127.0.0.1}:${VALKEY_PORT:-6207}:6379
        networks:
            shared-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - valkey7-data:/data
        tty: true

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    valkey7-data:
        name: valkey7-data
