services:
    caddy:
        container_name: caddy
        image: caddy
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
        ports:
            - ${CADDY_PORT_2019:-2019}:2020
            - ${CADDY_PORT_80:-80}:80
            - ${CADDY_PORT_443_TCP:-443}:443/tcp
            - ${CADDY_PORT_443_UDP:-443}:443/udp
        networks:
            shared-network-internal:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - caddy-data:/data
            - caddy-config:/config
            - caddy-certificate-authority:/data/caddy/pki/authorities/local
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - ./config:/etc/caddy/config:ro
            - ./sites:/etc/caddy/sites:ro

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_INTERNAL_NAME:-shared-network-internal}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-data:
        name: caddy-data
    caddy-config:
        name: caddy-config
    caddy-certificate-authority:
        name: caddy-certificate-authority
