services:
    joplin:
        container_name: joplin
        image: joplin/server
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            APP_BASE_URL: "${APP_BASE_URL:-https://${DOMAIN:-joplin.localhost}}"
            APP_PORT: "${APP_PORT:-22300}"
            DB_CLIENT: "${DB_CLIENT:-pg}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-joplin}"
            POSTGRES_DATABASE: "${POSTGRES_DATABASE:-joplin}"
            POSTGRES_USER: "${POSTGRES_USER:-joplin}"
            POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
            POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
        # ports:
        #     - ${JOPLIN_PORT:-22300}:22300
        networks:
            main:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.joplin.loadbalancer.server.port=8080"
            - "traefik.http.routers.joplin.rule=Host(`${DOMAIN:-joplin.localhost}`)"
            - "traefik.http.routers.joplin.entrypoints=http"
            - "traefik.http.routers.joplin.tls=false"
            - "traefik.http.routers.joplin.service=joplin"
            - "traefik.http.routers.joplin-secure.rule=Host(`${DOMAIN:-joplin.localhost}`)"
            - "traefik.http.routers.joplin-secure.entrypoints=https"
            - "traefik.http.routers.joplin-secure.tls=true"
            - "traefik.http.routers.joplin-secure.service=joplin"

networks:
    main:
        external: true
