services:
    caddy-labels:
        container_name: caddy-labels
        image: lucaslorentz/caddy-docker-proxy:ci
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            CADDY_INGRESS_NETWORKS: "${CADDY_INGRESS_NETWORKS:-shared-network}"
        ports:
            - ${CADDY_LABELS_PORT_2019:-2019}:2020
            - ${CADDY_LABELS_PORT_80:-8080}:80
            - ${CADDY_LABELS_PORT_443_TCP:-8443}:443/tcp
            - ${CADDY_LABELS_PORT_443_UDP:-8443}:443/udp
        networks:
            shared-network-internal:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - shared-home:/home/${APP_USER:-app}
            - caddy-labels-data:/data
            - caddy-labels-config:/config
        labels:
            caddy_0.servers.trusted_proxies: "static private_ranges"
            caddy_1: ":2020"
            caddy_1.reverse_proxy: "localhost:2019"

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_INTERNAL_NAME:-shared-network-internal}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-labels-data:
        name: caddy-labels-data
    caddy-labels-config:
        name: caddy-labels-config
