services:
    whoami:
        container_name: whoami
        image: traefik/whoami
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
        labels:
            caddy: "${DOMAIN:-whoami.localhost}"
            caddy.reverse_proxy: "{{upstreams http}}"

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
