services:
    dev:
        container_name: dev
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        user: "${UID:-1000}:${GID:-1000}"
        tty: true
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            XDG_CACHE_HOME: "${XDG_CACHE_HOME:-${HOME}/.cache}"
            XDG_CONFIG_HOME: "${XDG_CONFIG_HOME:-${HOME}/.config}"
            XDG_DATA_HOME: "${XDG_DATA_HOME:-${HOME}/.local/share}"
            XDG_STATE_HOME: "${XDG_STATE_HOME:-${HOME}/.local/state}"
            EDITOR: "${EDITOR:-nvim}"
            VISUAL: "${VISUAL:-nvim}"
            PAGER: "${PAGER:-less}"
            PNPM_HOME: "${PNPM_HOME:-${HOME}/.local/share/pnpm}"
            PHP_CS_FIXER_IGNORE_ENV: "${PHP_CS_FIXER_IGNORE_ENV:-1}"
        networks:
            main:
        # volumes:
        #     - ~:/home/dev

networks:
    main:
        external: true
