services:
    whoami:
        container_name: whoami
        image: traefik/whoami
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
        hostname: "${DOMAIN:-whoami.localhost}"
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.example-job.command: "uname -a"
            ofelia.job-exec.example-job.schedule: "0,20,40 * * * *"
            # ofelia.job-exec.example-job.schedule: "@every 5s"

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
